# # categories and sub categories for object type and material

# material_dict = {
#     'animal product': ['bone', 'ivory', 'leather', 'vellum', 'wool'],
#     'bark': [],
#     'ceramic': ['terracotta'],
#     'fabric/cloth': ['canvas', 'Linen'],
#     'gemstones': ['agate', 'diamond', 'turquoise'],
#     'glass': [],
#     'human remains': [],
#     'ink or dye': [],
#     'metal': ['brass', 'bronze', 'copper', 'gold', 'silver', 'steel'],
#     'paint': ['fresco', 'oil', 'tempera', 'watercolor'],
#     'paper': ['papier-mâché'],
#     'plaster': [],
#     'shell': [],
#     'stone': ['alabaster', 'basalt', 'chlorite', 'fuschite', 'granodiorite', 'limestone', 'marble', 'sandstone', 'soapstone', 'tuff'],
#     'wood': []
# }

# type_dict = {
#     'Amphora': [],
#     'Amulet': [],
#     'Animal Skeleton': [],
#     'Apparel': ['Belt'],
#     'Armor': [],
#     'Bead': [],
#     'Bell': [],
#     'Book': [],
#     'Bronze': [],
#     'Building': ['Column', 'Door', 'Strut', 'Window'],
#     'Bust': [],
#     'Candelabrum': [],
#     'Carving': [],
#     'Coffin': ['sarcophagus'],
#     'Coin': [],
#     'Cutlery': [],
#     'Cylinder Seal': [],
#     'Drawing': [],
#     'Figurine': [],
#     'Firearm': [],
#     'Folio': [],
#     'Food/Drink Container': ['Krater', 'Phiale'],
#     'Funerary Object': [],
#     'Furniture': ['Throne'],
#     'Game': [],
#     'Gemstone': [],
#     'Human Remains': [],
#     'Jewelry': ['Bracelet', 'Brooch', 'Ear ornament', 'Necklace'],
#     'Manuscript': ['Letter(s)'],
#     'Mask': [],
#     'Mold': [],
#     'Mosaic': [],
#     'Music Score': ['Choirbook'],
#     'Painting': [],
#     'Panel': ['Fresco', 'Mural', 'Relief'],
#     'Plaque or Tablet': [],
#     'Print': ['Monotype'],
#     'Relic': [],
#     'Relief': [],
#     'Religious Icon': [],
#     'Sculpture': ['Casting'],
#     'Seal': [],
#     'Shield': [],
#     'Sphinx': [],
#     'Statue': [],
#     'Stele': [],
#     'Storage container': ['Pithos'],
#     'Textile': [],
#     'Timepiece': [],
#     'Tombstone': [],
#     'Tool': [],
#     'Totem Pole': [],
#     'Vase': [],
#     'Vessel': [],
#     'Weapon': ['Axe', 'Spearhead'],
#     'Weight': []
# }
